[package]
name = "CustomCanvas"
version = "0.1.0"
authors = ["any_one <git@any_gui.com>"]
edition = "2024"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["canvas", "tokio", "debug"]
lyon.workspace = true